// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package v1

import (
	"gf_study/api/v1"
)

type ControllerUser struct{}

func NewUser() v1.IV1User {
	return &ControllerUser{}
}
