// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_study/internal/dao/internal"
)

// gfGoodsDao is the data access object for the table gf_goods.
// You can define custom methods on it to extend its functionality as needed.
type gfGoodsDao struct {
	*internal.GfGoodsDao
}

var (
	// GfGoods is a globally accessible object for table gf_goods operations.
	GfGoods = gfGoodsDao{internal.NewGfGoodsDao()}
)

// Add your custom methods and functionality below.