// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf_study/internal/dao/internal"
)

// gfUsersDao is the data access object for the table gf_users.
// You can define custom methods on it to extend its functionality as needed.
type gfUsersDao struct {
	*internal.GfUsersDao
}

var (
	// GfUsers is a globally accessible object for table gf_users operations.
	GfUsers = gfUsersDao{internal.NewGfUsersDao()}
)

// Add your custom methods and functionality below.
